# Add your own funding links here to show a "Sponsor" button on the repository.
# Docs: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
#
# Examples (uncomment and fill in):
# github: [ Gh0s777tt ]
# ko_fi: your-username
# patreon: your-username
# custom: [ "https://example.com/donate" ]
